---
- hosts: ec2
  become: true
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /root/demo-app
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfil
      copy:
        src: ./app/.
        dest: /root/demo-app/
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: myapp:v1.0
        path: /root/demo-app/
        source: build
        state: present